# Extends https://github.com/mundialis/github-workflows/blob/main/linting-config-examples/ruff.toml

lint.ignore = [
    "A001",
    "ANN001",
    "ANN002",
    "ANN201",
    "ANN202",
    "ANN204",
    "ARG002",
    "BLE001",
    "COM812",
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "D200",
    "D202",
    "D205",
    "D212",
    "D400",
    "D401",
    "D413",
    "D415",
    "D417",
    "FBT002",
    "FURB101",
    "I001",
    "ISC001",
    "ISC003",
    "PERF401",
    "PLC1901",
    "PLR0904",
    "PLR0911",
    "PLR0912",
    "PLR0914",
    "PLR0915",
    "PLR2004",
    "PLR6201",
    "PLR6301",
    "PLW0127",
    "PLW1514",
    "PT009",
    "PTH102",
    "PTH107",
    "PTH110",
    "PTH113",
    "PTH118",
    "PTH120",
    "PTH123",
    "PTH208",
    "RET505",
    "RUF012",
    "S110",
    "S301",
    "S403",
    "SIM102",
    "SIM105",
    "SIM115",
    "SIM300",
    "TRY003",
    "UP009",
    "UP015",
    "UP031",
    # for tests
    "PLW0603",
    "S606",
    "PLR0913",
    "PLR0917",
    "S107",
]

[lint.per-file-ignores]
"tests/*" = [
    "FURB103",
    "S108",
    "S113",
]
